// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonaLite.Infrastructure.Data;

#nullable disable

namespace PersonaLite.Infrastructure.Migrations
{
    [DbContext(typeof(PersonaLiteDbContext))]
    partial class PersonaLiteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("PersonaLite.Domain.Entities.DiaDeTreino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlanoTreinoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlanoTreinoId");

                    b.ToTable("DiasDeTreino");
                });

            modelBuilder.Entity("PersonaLite.Domain.Entities.ExercicioPlanejado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DiaDeTreinoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrupoMuscular")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepeticoesAlvo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeriesAlvo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiaDeTreinoId");

                    b.ToTable("ExerciciosPlanejados");
                });

            modelBuilder.Entity("PersonaLite.Domain.Entities.FotoProgresso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Angulo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RegistroMedidasId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FotosProgresso");
                });

            modelBuilder.Entity("PersonaLite.Domain.Entities.PlanoTreino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FimVigencia")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("InicioVigencia")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlanosTreino");
                });

            modelBuilder.Entity("PersonaLite.Domain.Entities.RegistroMedidas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("TEXT");

                    b.Property<double>("Imc")
                        .HasColumnType("REAL");

                    b.Property<double>("PercentualGorduraJP7")
                        .HasColumnType("REAL");

                    b.Property<double>("PesoKg")
                        .HasColumnType("REAL");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RegistrosMedidas");
                });

            modelBuilder.Entity("PersonaLite.Domain.Entities.SessaoExercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExercicioPlanejadoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SessoesExercicio");
                });

            modelBuilder.Entity("PersonaLite.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("AlturaCm")
                        .HasColumnType("REAL");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sexo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PersonaLite.Domain.Entities.DiaDeTreino", b =>
                {
                    b.HasOne("PersonaLite.Domain.Entities.PlanoTreino", null)
                        .WithMany("Dias")
                        .HasForeignKey("PlanoTreinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonaLite.Domain.Entities.ExercicioPlanejado", b =>
                {
                    b.HasOne("PersonaLite.Domain.Entities.DiaDeTreino", null)
                        .WithMany("Exercicios")
                        .HasForeignKey("DiaDeTreinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonaLite.Domain.Entities.RegistroMedidas", b =>
                {
                    b.OwnsOne("PersonaLite.Domain.ValueObjects.Circunferencias", "Circunferencias", b1 =>
                        {
                            b1.Property<Guid>("RegistroMedidasId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("AntebracoDireitoCm")
                                .HasColumnType("REAL");

                            b1.Property<double>("AntebracoEsquerdoCm")
                                .HasColumnType("REAL");

                            b1.Property<double>("BracoDireitoCm")
                                .HasColumnType("REAL");

                            b1.Property<double>("BracoEsquerdoCm")
                                .HasColumnType("REAL");

                            b1.Property<double>("CinturaCm")
                                .HasColumnType("REAL");

                            b1.Property<double>("PanturrilhaDireitaCm")
                                .HasColumnType("REAL");

                            b1.Property<double>("PanturrilhaEsquerdaCm")
                                .HasColumnType("REAL");

                            b1.Property<double>("PernaDireitaCm")
                                .HasColumnType("REAL");

                            b1.Property<double>("PernaEsquerdaCm")
                                .HasColumnType("REAL");

                            b1.Property<double>("PescocoCm")
                                .HasColumnType("REAL");

                            b1.Property<double>("QuadrilCm")
                                .HasColumnType("REAL");

                            b1.Property<double>("ToraxMamiloCm")
                                .HasColumnType("REAL");

                            b1.Property<double>("ToraxMesoesternalCm")
                                .HasColumnType("REAL");

                            b1.Property<double>("UltimaCostelaCm")
                                .HasColumnType("REAL");

                            b1.HasKey("RegistroMedidasId");

                            b1.ToTable("RegistrosMedidas");

                            b1.WithOwner()
                                .HasForeignKey("RegistroMedidasId");
                        });

                    b.OwnsOne("PersonaLite.Domain.ValueObjects.DobrasCutaneas", "Dobras", b1 =>
                        {
                            b1.Property<Guid>("RegistroMedidasId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("AbdominalMm")
                                .HasColumnType("REAL");

                            b1.Property<double>("AxilarMediaMm")
                                .HasColumnType("REAL");

                            b1.Property<double>("CoxaMm")
                                .HasColumnType("REAL");

                            b1.Property<double>("PeitoralMm")
                                .HasColumnType("REAL");

                            b1.Property<double>("SubescapularMm")
                                .HasColumnType("REAL");

                            b1.Property<double>("SuprailiacaMm")
                                .HasColumnType("REAL");

                            b1.Property<double>("TricepsMm")
                                .HasColumnType("REAL");

                            b1.HasKey("RegistroMedidasId");

                            b1.ToTable("RegistrosMedidas");

                            b1.WithOwner()
                                .HasForeignKey("RegistroMedidasId");
                        });

                    b.Navigation("Circunferencias")
                        .IsRequired();

                    b.Navigation("Dobras")
                        .IsRequired();
                });

            modelBuilder.Entity("PersonaLite.Domain.Entities.SessaoExercicio", b =>
                {
                    b.OwnsMany("PersonaLite.Domain.Entities.SerieRealizada", "Series", b1 =>
                        {
                            b1.Property<Guid>("SessaoExercicioId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<double>("CargaKg")
                                .HasColumnType("REAL");

                            b1.Property<int>("GrupoSerie")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("OrdemEstagio")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Repeticoes")
                                .HasColumnType("INTEGER");

                            b1.HasKey("SessaoExercicioId", "Id");

                            b1.ToTable("SerieRealizada");

                            b1.WithOwner()
                                .HasForeignKey("SessaoExercicioId");
                        });

                    b.Navigation("Series");
                });

            modelBuilder.Entity("PersonaLite.Domain.Entities.DiaDeTreino", b =>
                {
                    b.Navigation("Exercicios");
                });

            modelBuilder.Entity("PersonaLite.Domain.Entities.PlanoTreino", b =>
                {
                    b.Navigation("Dias");
                });
#pragma warning restore 612, 618
        }
    }
}
